---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

We simulate the bites dyads as a poisson process with parameter $\lambda$ (bites per minute) in the following fashion:

Both processes, with and without mimicry, will have a length of $l \sim U(\underline{l}, \overline{l})$, this is the maximum length of the meal.

Independent process: Simply, for each individual $i\in\{1,2\}$ we draw time intervals $t_{ib}\sim\mbox{Exp}(\lambda)$, $b$ indexing by the number of bite, until the cumulative sum of it reaches $l$.

For the dependent process: Let $m_i \in [0,1]$ denote the propensity to mimicry of individual i. We start the algorithm by randomly choosing which individual starts, WLOG individual $i$ starts. We set the initial draw for each individual to be $t_{i0} = 0$.

1.  If $j$ was the last one to draw, then $k$ will draw $t_{kt} \sim \mbox{Exp}\left(\lambda_k(1 - m_k) + (t_{it-1} - t_{k-1})^{-1}m_k\right)$, otherwise we set $t_{kt} \sim \mbox{Exp}\left(\lambda_k\right)$.

2.  If $\sum_t t_{kt} \geq l$, stop.
