---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = ".8\\linewidth",
  fig.width = 10
)
```

<!-- We simulate the bites dyads as a poisson process with parameter $\lambda$ (bites per minute) in the following fashion: -->

<!-- Both processes, with and without mimicry, will have a length of $l \sim U(\underline{l}, \overline{l})$, this is the maximum length of the meal. -->

<!-- Independent process: Simply, for each individual $i\in\{1,2\}$ we draw time intervals $t_{ib}\sim\mbox{Exp}(\lambda)$, $b$ indexing by the number of bite, until the cumulative sum of it reaches $l$. -->

<!-- For the dependent process: Let $m_i \in [0,1]$ denote the propensity to mimicry of individual i. We start the algorithm by randomly choosing which individual starts, WLOG individual $i$ starts. We set the initial draw for each individual to be $t_{i0} = 0$. -->

<!-- 1.  If $j$ was the last one to draw, then $k$ will draw $t_{kt} \sim \mbox{Exp}\left(\lambda_k(1 - m_k) + (t_{it-1} - t_{k-1})^{-1}m_k\right)$, otherwise we set $t_{kt} \sim \mbox{Exp}\left(\lambda_k\right)$. -->

<!-- 2.  If $\sum_t t_{kt} \geq l$, stop. -->

```{r, eval=TRUE, echo=FALSE, cache=TRUE}
library(biteme)

# Loading the data
fnames <- list.files("~/Dropbox/Bite data (deidentified)/All bites/", pattern = "dyad", full.names = TRUE)
dyads  <- lapply(fnames, readr::read_csv)

# Turning times into integers
dyads <- lapply(dyads, function(x) {
  x$BiteTime_hms <- as.integer(x$BiteTime_hms)
  as.matrix(x[,1:2])
})

# Defining the statistic
# Difference between i and j
stat <- function(x) {

  # Only pairs that are different
  x <- x[dplyr::lag(x[,2,drop=TRUE]) != x[,2,drop=TRUE],,drop=FALSE]
  
  if (nrow(x) == 1)
    return(NA)
  
  y <- dplyr::lag(x[,1,drop=TRUE])
  mean(x[,1,drop=TRUE] - y, na.rm=TRUE)
}

# Running the permutation tests
cl <- parallel::makeForkCluster(12)
ans01 <- perm_test(dyads[[2]], stat, R = 1e4, cl = cl)
ans02 <- perm_test(dyads[[2]], biteme:::timegap, R = 1e4, cl = cl)

ans <- lapply(
  dyads, perm_test, statistic = biteme:::timegap, R = 500000, cl = cl
  )
parallel::stopCluster(cl)
```

```{r}
# lapply(ans, plot, breaks=100L, main = c(expression(i %->% j),expression(j %->% i)))
plot(ans[[23]], breaks=100, main = c(expression(i %->% j),expression(j %->% i)))
plot(ans[[22]], breaks=100, main = c(expression(i %->% j),expression(j %->% i)))
```

```{r}
pvals<-as.vector(t(sapply(ans, "[[", "pval")))
names(pvals) <- c(
  sprintf("%2i(a)", as.integer(stringr::str_extract(fnames, "[0-9]+"))),
  sprintf("%2i(b)", as.integer(stringr::str_extract(fnames, "[0-9]+")))
  )
pvals <- sort(pvals)
cols <- rep("tomato", length(pvals))
cols[which(pvals <= .05)] <- "steelblue"
barplot(pvals, las=2, cex.names=1, col=cols, border=NA)
abline(h=.05, lwd=2, lty=2)
text(x = 2, y = .05, labels = "p-value 0.05", pos = 3)
title(
  "p-values from the permuitation tests",
  xlab = "Dyad",
  ylab = "p-value"
)
```


