// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// simulate_dyad
std::vector< std::vector< double > > simulate_dyad(NumericVector rates, NumericVector mimicry, double meal_length, int maxiter);
RcppExport SEXP _biteme_simulate_dyad(SEXP ratesSEXP, SEXP mimicrySEXP, SEXP meal_lengthSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type rates(ratesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mimicry(mimicrySEXP);
    Rcpp::traits::input_parameter< double >::type meal_length(meal_lengthSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_dyad(rates, mimicry, meal_length, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// shuffle_bites_sorted
List shuffle_bites_sorted(arma::imat data, const std::vector< arma::uvec >& ids);
RcppExport SEXP _biteme_shuffle_bites_sorted(SEXP dataSEXP, SEXP idsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::imat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const std::vector< arma::uvec >& >::type ids(idsSEXP);
    rcpp_result_gen = Rcpp::wrap(shuffle_bites_sorted(data, ids));
    return rcpp_result_gen;
END_RCPP
}
// shuffle_bites_unsorted
List shuffle_bites_unsorted(arma::imat data);
RcppExport SEXP _biteme_shuffle_bites_unsorted(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::imat >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(shuffle_bites_unsorted(data));
    return rcpp_result_gen;
END_RCPP
}
// timegap
NumericVector timegap(const NumericMatrix& data);
RcppExport SEXP _biteme_timegap(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(timegap(data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_biteme_simulate_dyad", (DL_FUNC) &_biteme_simulate_dyad, 4},
    {"_biteme_shuffle_bites_sorted", (DL_FUNC) &_biteme_shuffle_bites_sorted, 2},
    {"_biteme_shuffle_bites_unsorted", (DL_FUNC) &_biteme_shuffle_bites_unsorted, 1},
    {"_biteme_timegap", (DL_FUNC) &_biteme_timegap, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_biteme(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
