# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.simulate_dyad <- function(rates, mimicry, meal_length = 1.0, maxiter = 1000L) {
    .Call(`_biteme_simulate_dyad`, rates, mimicry, meal_length, maxiter)
}

.shuffle_bites <- function(data) {
    .Call(`_biteme_shuffle_bites`, data)
}

