# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.simulate_dyad <- function(rates, mimicry, meal_length = 1.0, maxiter = 1000L) {
    .Call(`_biteme_simulate_dyad`, rates, mimicry, meal_length, maxiter)
}

#' Shuffle bite data by sorting the intervals at individual level
#' @param data A two-column integer matrix. The first column holds the times,
#' while the second column holds the individual ids.
#' @return A shuffled version of the data
#' @export
shuffle_bites <- function(data) {
    .Call(`_biteme_shuffle_bites`, data)
}

